package main

// Generator stubs. {{.Name}} is PascalCase, {{.Snake}} snake_case,
// {{.Camel}} camelCase, {{.Plural}} plural snake_case.

const controllerStub = `package controllers

import (
	"flux/app/dto"
	"flux/app/services"
	"flux/framework"
)

// {{.Name}}Controller is a RESTful resource controller. Register it with:
//
//	route.Resource("/{{.Plural}}", controllers.New{{.Name}}Controller(service))
type {{.Name}}Controller struct {
	service *services.{{.Name}}Service
}

func New{{.Name}}Controller(service *services.{{.Name}}Service) *{{.Name}}Controller {
	return &{{.Name}}Controller{service: service}
}

// Index — GET /{{.Plural}}
func (c *{{.Name}}Controller) Index(req *framework.Request) {
	req.View("{{.Name}}s/Index", dto.{{.Name}}IndexDTO{})
}

// Create — GET /{{.Plural}}/create
func (c *{{.Name}}Controller) Create(req *framework.Request) {
	req.View("{{.Name}}s/Create", nil)
}

// Store — POST /{{.Plural}}
func (c *{{.Name}}Controller) Store(req *framework.Request) {
	var input dto.Create{{.Name}}DTO
	if !req.Validate(&input) {
		return
	}

	// TODO: call c.service, then redirect.
	req.Redirect("/{{.Plural}}")
}

// Show — GET /{{.Plural}}/:id
func (c *{{.Name}}Controller) Show(req *framework.Request) {
	req.View("{{.Name}}s/Show", nil)
}

// Edit — GET /{{.Plural}}/:id/edit
func (c *{{.Name}}Controller) Edit(req *framework.Request) {
	req.View("{{.Name}}s/Edit", nil)
}

// Update — PUT /{{.Plural}}/:id
func (c *{{.Name}}Controller) Update(req *framework.Request) {
	var input dto.Update{{.Name}}DTO
	if !req.Validate(&input) {
		return
	}

	// TODO: call c.service, then redirect.
	req.Redirect("/{{.Plural}}")
}

// Destroy — DELETE /{{.Plural}}/:id
func (c *{{.Name}}Controller) Destroy(req *framework.Request) {
	// TODO: call c.service, then redirect.
	req.Redirect("/{{.Plural}}")
}
`

const modelStub = `package models

import "gorm.io/gorm"

// {{.Name}} is a GORM model. Only database concerns belong here.
type {{.Name}} struct {
	gorm.Model

	// TODO: add columns, e.g.:
	// Title string ` + "`" + `gorm:"size:255;not null"` + "`" + `
}
`

const serviceStub = `package services

import (
	"context"

	"gorm.io/gorm"
)

// {{.Name}}Service holds the business logic for {{.Plural}}.
type {{.Name}}Service struct {
	db *gorm.DB
}

func New{{.Name}}Service(db *gorm.DB) *{{.Name}}Service {
	return &{{.Name}}Service{db: db}
}

// Get{{.Name}}s returns all {{.Plural}}.
func (s *{{.Name}}Service) Get{{.Name}}s(ctx context.Context) error {
	// TODO: query with s.db.WithContext(ctx) and map models to DTOs.
	return nil
}
`

const dtoStub = `package dto

// {{.Name}}DTO is the public shape of a {{.Camel}} sent to the frontend.
type {{.Name}}DTO struct {
	ID uint ` + "`" + `json:"id"` + "`" + `
	// TODO: add fields.
}

// {{.Name}}IndexDTO — props for Pages/{{.Name}}s/Index.vue.
type {{.Name}}IndexDTO struct {
	{{.Name}}s []{{.Name}}DTO ` + "`" + `json:"{{.Plural}}"` + "`" + `
}

// Create{{.Name}}DTO is the validated input for creating a {{.Camel}}.
type Create{{.Name}}DTO struct {
	// TODO: add fields with validate tags, e.g.:
	// Title string ` + "`" + `json:"title" validate:"required,max=255"` + "`" + `
}

// Update{{.Name}}DTO is the validated input for updating a {{.Camel}}.
type Update{{.Name}}DTO struct {
	// TODO: add fields with validate tags.
}
`

const middlewareStub = `package middleware

import (
	"flux/framework"
)

// {{.Name}} middleware. Call next() to continue; return without calling it
// to abort (write a response first).
func {{.Name}}() framework.Middleware {
	return func(req *framework.Request, next func()) {
		// TODO: inspect req, then:
		next()
	}
}
`

const migrationStub = `package migrations

import (
	"gorm.io/gorm"

	"flux/database"
)

func init() {
	database.RegisterMigration(database.Migration{
		ID: "{{.Timestamp}}_{{.Snake}}",
		Up: func(db *gorm.DB) error {
			// TODO: e.g. return db.AutoMigrate(&models.Post{})
			return nil
		},
	})
}
`

const pageStub = `<script setup lang="ts">
import DashboardLayout from '@/Layouts/DashboardLayout.vue'

// Props arrive automatically from req.View("{{.PagePath}}", dto)
defineProps<{
  // TODO: mirror your DTO fields here.
}>()
</script>

<template>
  <DashboardLayout title="{{.Name}}">
    <div class="rounded-xl border bg-card p-6 text-card-foreground shadow-sm">
      <h2 class="text-lg font-semibold">{{.Name}}</h2>
      <p class="mt-2 text-sm text-muted-foreground">
        Generated by flux make:page — edit resources/js/Pages/{{.PagePath}}.vue
      </p>
    </div>
  </DashboardLayout>
</template>
`
